### ISSUE TITLE
SecurityException regarding ConnectivityManager on Android 11

### ISSUE THREAD

**Issue by silviorp** [bugsnag/bugsnag-android-performance#271]
### Describe the bug
I'm getting the following Exception while starting BugsnagPerformance:
```
Caused by: java.lang.SecurityException: Package android does not belong to 10920
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2374)
        at android.os.Parcel.createException(Parcel.java:2358)
        at android.os.Parcel.readException(Parcel.java:2341)
        at android.os.Parcel.readException(Parcel.java:2283)
        at android.net.IConnectivityManager$Stub$Proxy.getNetworkCapabilities(IConnectivityManager.java:2456)
        at android.net.ConnectivityManager.getNetworkCapabilities(ConnectivityManager.java:1385)
        at com.bugsnag.android.performance.internal.ConnectivityApi24.<init>(ConnectivityApi24:153)
        at com.bugsnag.android.performance.internal.Connectivity$Factory.newInstance(Connectivity:73)
        at com.bugsnag.android.performance.BugsnagPerformance.startUnderLock(BugsnagPerformance:106)
        at com.bugsnag.android.performance.BugsnagPerformance.start(BugsnagPerformance:72)
        at com.bugsnag.android.performance.BugsnagPerformance.start(BugsnagPerformance:58)
        at br.com.p20.initializers.AnalyticsSdksInitializer.startBugsnag(AnalyticsSdksInitializer:74)
```

Looks like it's a known problem reported in several other libraries and even to Google References:
https://issuetracker.google.com/issues/175055271
https://stackoverflow.com/a/78400921

Datadog fix for same problem: https://github.com/microsoft/cpp_client_telemetry/pull/798/files

### Steps to reproduce
1. Initialize BugsnagPerformance on Android 11.
2. `BugsnagPerformance.start(context, keys.bugsnagKey.key)`

### Environment
* BugSnag Performance library version: 1.5.0
* BugSnag Error Monitoring library version (if any): 6.6.0
* Android version: 11
*  Emulator or physical device: Phisical Devices (in production)

It looks like that the solution would be just adding a try/catch returning `null` into `Connectivity.kt` surrounding the call `cm.getNetworkCapabilities(cm.activeNetwork)`in line 153.

**Comment by clr182** [comment]
Hi @silviorp 

Thank you for reaching out and sharing this known issue with us. 

We've added an item to our backlog to address this. While I don't currently have a clear ETA, we will be sure to update you via this thread once we have a release in place.

**Comment by clr182** [comment]
Hi @silviorp  

Thank you for your patience as we investigated this issue further. 

We have just put out a new `Bugsnag-android-performance` release v1.7.0 which should solve this issue you are facing with Android 11 crashes. https://github.com/bugsnag/bugsnag-android-performance/releases/tag/v1.7.0 

After upgrading to the latest version of the SDK, if you are still experiencing issues then please let us know and we can investigate further
