### ISSUE TITLE
Untagged socket violation when StrictMode is enabled

### ISSUE THREAD

**Issue by mikejeep** [bugsnag/bugsnag-android-performance#297]
### Describe the bug
The BugSnag performance module throws an untagged socket violation when StrictMode is enabled.

### Environment
* BugSnag Performance library version: 1.9.0
* BugSnag Error Monitoring library version (if any):  6.8.0
* Android version: 15
*  Emulator or physical device: Pixel 8

### Logcat output
```
StrictMode policy violation: android.os.strictmode.UntaggedSocketViolation: Untagged socket detected; use TrafficStats.setTrafficStatsTag() to track all network usage (Ask Gemini)
at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2305)
at android.os.StrictMode.noteUntaggedSocket(StrictMode.java:2789)
at android.net.TrafficStats$SocketTagger.tag(TrafficStats.java:256)
at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:55)
at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:404)
at libcore.io.ForwardingOs.socket(ForwardingOs.java:821)
at libcore.io.IoBridge.socket(IoBridge.java:840)
at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:128)
at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:128)
at java.net.Socket.createImpl(Socket.java:514)
at java.net.Socket.getImpl(Socket.java:577)
at java.net.Socket.setSoTimeout(Socket.java:1203)
at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
at com.bugsnag.android.performance.internal.HttpDelivery.deliver(HttpDelivery.kt:59)
at com.bugsnag.android.performance.internal.HttpDelivery.deliver(HttpDelivery.kt:32)
at com.bugsnag.android.performance.internal.RetryDelivery.deliver(RetryDelivery.kt:17)
at com.bugsnag.android.performance.internal.SendBatchTask.execute(SendBatchTask.kt:18)
at com.bugsnag.android.performance.internal.Worker.runTasks(Worker.kt:146)
at com.bugsnag.android.performance.internal.Worker.run(Worker.kt:94)
at java.lang.Thread.run(Thread.java:1012)
```

**Comment by toniewypada** [comment]
Hi @mikejeep 👋🏻,
We have put out a new Bugsnag-android-performance [release v1.10.0 ](https://github.com/bugsnag/bugsnag-android-performance/releases/tag/v1.10.0)which should solve this issue you are facing. 

After upgrading to the latest version of the SDK, if you are still experiencing issues then please let us know and we can investigate further.
